const { DiodeClientManager } = require('../index');

const keyLocation = './db/keys.json';
const initialFleetContract = process.env.DIODE_FLEET_CONTRACT || '0x1111111111111111111111111111111111111111';
const nextFleetContract = process.env.DIODE_NEXT_FLEET_CONTRACT || '0x2222222222222222222222222222222222222222';
const shouldConnect = process.env.DIODE_CONNECT === 'true';

async function main() {
  const client = new DiodeClientManager({
    keyLocation,
    fleetContract: initialFleetContract,
  });

  console.log('Initial manager fleet contract:', client.fleetContract);

  if (!shouldConnect) {
    client.setFleetContract(nextFleetContract);
    console.log('Updated manager fleet contract:', client.fleetContract);
    console.log('Set DIODE_CONNECT=true to connect and observe the updated contract on active relay connections.');
    return;
  }

  try {
    await client.connect();
    console.log(`Connected relay count: ${client.getConnections().length}`);
    for (const connection of client.getConnections()) {
      console.log(`Before update ${connection.host}:${connection.port} fleet contract: ${connection.fleetContractHex}`);
    }

    client.setFleetContract(nextFleetContract);
    console.log('Updated manager fleet contract:', client.fleetContract);
    for (const connection of client.getConnections()) {
      console.log(`After update ${connection.host}:${connection.port} fleet contract: ${connection.fleetContractHex}`);
    }

    console.log('The new fleet contract will be used on the next ticket generated by each connection.');
  } finally {
    client.close();
  }
}

main().catch((error) => {
  console.error('Fleet contract example failed:', error);
  process.exitCode = 1;
});
